cmake_minimum_required(VERSION 3.31)
project(DataStruct_cpp)

set(CMAKE_CXX_STANDARD 17)

add_executable(DataStruct_cpp
#        SeqBST.cpp
        LinkedBT.cpp
        #        Infix_to_Suffix.cpp
#        Eight_Queen.cpp
#        Maze.cpp
#        Infix_Expression_evaluator.cpp
        SeqQueue.h
#        LinkedQueue.h
#        LinkedStack.h
#        CyclicLL.cpp
#        CyclicLL.h
#        SeqList.h
#        AcademicClass.cpp
#        AcademicClass.h
#        LinkedList.h
#        DLinkedList.h
#        SeqStack.h
#        Polynomial.cpp
#        Polynomial.h
)
